### PR TITLE
add more dns server

### PR DESCRIPTION
**Pull request by huitc**
**cloudflare: 1.1.1.1
alidns (alibaba): 223.5.5.5
Some Chinese websites will be better if you use alidns**

google translate ^^''

### CODE REVIEW

**Comment by huitc** [comment]
just this one:
https://github.com/fleetcaptain/Turbolist3r/pull/7/commits/b4b2c47e4c126738f1b7665311246a61d3f20208

**Comment by huitc** [comment]
baidu dns:
```
180.76.76.76
2400:da00::6666
```

**Comment by fleetcaptain** [comment]
It appears this commit references sublist3r.py? Instead of turbolist3r.py? GitHub won't let me perform a normal merge due to this conflict. 

Of the listed resolvers, Cloudflare resolvers (1.1.1.1 and 1.0.0.1) are already in Turbolist3r. Makes sense that alidns would work better for Chinese located users and site, but for anyone outside China they could add latency and otherwise not be ideal. User experience would improve for some, but degrade for others.

A better solution could be give the user the option at runtime to specify custom resolvers. Perhaps directly in an argument, or read from a file. It would be nice to have, if you want to implement this functionality feel free to submit a pull request. If not implemented sooner I'll try to add it myself next time I work on the project.

**Comment by fleetcaptain** [comment]
Closing because:
- Cloudflare resolvers already present
- Alidns resolvers could impact performance for users outside Asia Pacific region

I do like the idea of allowing users to supply resolvers at runtime. Will try to integrate at some point

**Comment by fleetcaptain** [comment]
I added the ability to supply DNS resolvers for the analysis module at runtime to Turbolist3r. You can create a file with the DNS servers you want and tell Turbolist3r to use them with -r/--resolvers. Thanks for suggesting this feature!

**Pull request closed without merging**
